sudo: required
dist: trusty
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-25

    #: Add android image
    - sys-img-armeabi-v7a-android-25
    - extra-android-m2repository

branches:
  only:
    - master

before_install:
  #: Setup Android SDK
  - sudo dpkg --add-architecture i386
  - sudo apt update
  - sudo apt install -y build-essential ccache git zlib1g-dev python2.7 python2.7-dev python-virtualenv libncurses5:i386 libstdc++6:i386 zlib1g:i386 unzip ant ccache autoconf libtool
  - sudo apt install -y openjdk-8-jdk

  #: Log where android is
  - which adb
  - which android
  #- which ndk-build

  # Start the emulator!
  - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator

  #: What encoding is travis using?
  - echo $LANG
  - python -c "from locale import getpreferredencoding; print(getpreferredencoding())"

  #: Install Crystax NDK
  - mkdir ~/Android
  - mkdir ~/Android/Crystax
  - wget https://www.crystax.net/download/crystax-ndk-10.3.2-linux-x86_64.tar.xz
  - tar xf crystax-ndk-10.3.2-linux-x86_64.tar.xz -C ~/Android/Crystax

  # Create python virtualenv
  - virtualenv ~/venv
  - source ~/venv/bin/activate
  - python --version
  - pip --version

  #: Install cython
  - pip install Cython --install-option="--no-cython-compile"

  # Install cli dependencies
  - pip install sh colorama appdirs six jinja2 pipdeptree atom ply

  # Intall test tools
  - pip install pytest pytest-cov pytest-catchlog pytest-timeout

  # Install codecov report tools
  - pip install codecov

install:

  # Install enamlnative (check that build script is not broken
  - cd $TRAVIS_BUILD_DIR
  - python setup.py develop
  - cd ~


script:

  # Run the enaml-native test suite
  - cd $TRAVIS_BUILD_DIR
  - py.test tests --cov-report xml -v

after_success:
  - cd $TRAVIS_BUILD_DIR
  - codecov