sudo: required
dist: trusty
language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-25

branches:
  only:
    - master

before_install:
  #: Setup Android SDK
  - sudo dpkg --add-architecture i386
  - sudo apt update
  - sudo apt install -y build-essential ccache git zlib1g-dev python2.7 python2.7-dev libncurses5:i386 libstdc++6:i386 zlib1g:i386 unzip ant ccache autoconf libtool
  - sudo apt install -y openjdk-8-jdk


  #: Install Crystax NDK
  - mkdir ~/Android
  - mkdir ~/Android/Crystax
  - wget https://www.crystax.net/download/crystax-ndk-10.3.2-linux-x86_64.tar.xz
  - tar xf crystax-ndk-10.3.2-linux-x86_64.tar.xz -C ~/Android/Crystax

  # Just to be sure
  - pip install -U pip

  # pip is not able to install distribute: "ImportError: No module named _markerlib"
  - easy_install distribute

  #: Install cython
  - pip install Cython --install-option="--no-cython-compile"

  # Install cli dependencies
  - pip install sh colorama appdirs six jinja2 pipdeptree atom ply

  # Intall test tools
  - pip install pytest pytest-cov pytest-catchlog pytest-timeout

  # Install codecov report tools
  - pip install codecov

install:

  # Install enamlnative (check that build script is not broken
  - cd $TRAVIS_BUILD_DIR
  - python setup.py develop
  - cd ~

script:
  # Run the enaml test suite
  - cd $TRAVIS_BUILD_DIR
  - py.test tests --cov-report xml -v

after_success:
  - cd $TRAVIS_BUILD_DIR
  - codecov